FROM ghcr.io/radicalgrimoire/docker-helixcore/helix-p4d:latest

LABEL maintainer "ueno.s <ueno.s@gamestudio.co.jp>"
COPY files/get-keyvault-certificate.sh /usr/local/bin/get-keyvault-certificate.sh

CMD ["/usr/local/bin/run.sh"]
