name: build-test

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      docker_files_name: Dockerfile
      image_name: helix-p4d
      version_substr: ''
    secrets: inherit

  test-v2:
    uses: ./.github/workflows/test.yml
    with:
      docker_files_name: Dockerfile.v2
      image_name: helix-p4d
      version_substr: ''
    secrets: inherit
  