name: build-test

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      docker_files_name: Dockerfile
      image_name: helix-p4d
      version_substr: ''
      version: ${{ vars.VERSION }}
      p4root: ${{ vars.P4ROOT }}
      p4name: ${{ vars.P4NAME }}
      p4port: ${{ vars.P4PORT }}
      p4home: ${{ vars.P4HOME }}
      case_insensitive: ${{ vars.CASE_INSENSITIVE }}
    secrets: inherit
