name: build-test.v2

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile.v2'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      docker_files_name: Dockerfile.v2
    secrets: inherit