name: publish

env:
  TAG_LATEST: latest
  TAG_NIGHTLY: nightly

on:
  workflow_call:
    outputs:
      version:
        description: "The version of helix-p4d installed in the container (sanitized for tags)"
        value: ${{ jobs.publish.outputs.version }}
      version_raw:
        description: "The raw version of helix-p4d installed in the container"
        value: ${{ jobs.publish.outputs.version_raw }}


jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  # TAG_SUFFIX="nightly-$(date +'%Y%m%d')"
  publish:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.p4d-version.outputs.version }}
      version_raw: ${{ steps.p4d-version.outputs.raw_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ secrets.IMAGE_NAME }}

      - name: Load Docker image
        run: |
            docker load < ${{ secrets.IMAGE_NAME }}.tar
            echo "Loaded Docker image: ${{ secrets.IMAGE_NAME }}"
            docker images | grep ${{ secrets.IMAGE_NAME }}

      - name: Get P4D version from container
        id: p4d-version
        run: |
          VERSION_RAW=$(docker run --rm ${{ secrets.IMAGE_NAME }} sh -c "dpkg -l | grep helix-p4d" | awk '{print $3}' | head -1 || echo "unknown")
          VERSION=$(echo "$VERSION_RAW" | grep -oE "20[0-9]{2}\.[0-9]+" | head -1 || echo "unknown")
          echo "raw_version=$VERSION_RAW" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ secrets.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION="${{ steps.p4d-version.outputs.version }}"
          
          # P4Dバージョン + ビルド番号タグ
          docker tag ${{ secrets.IMAGE_NAME }} $IMAGE_ID:$VERSION.$GITHUB_RUN_NUMBER
          docker push $IMAGE_ID:$VERSION.$GITHUB_RUN_NUMBER

          # 最新タグ
          docker tag ${{ secrets.IMAGE_NAME }} $IMAGE_ID:${{ env.TAG_LATEST }}
          docker push $IMAGE_ID:${{ env.TAG_LATEST }}

          # ナイトリータグ（スケジュール実行時のみ）
          if [ "${{ github.event_name }}" == "schedule" ]; then
            docker tag ${{ secrets.IMAGE_NAME }} $IMAGE_ID:${{ env.TAG_NIGHTLY }}
            docker push $IMAGE_ID:${{ env.TAG_NIGHTLY }}
          fi
          