name: test

on:
  workflow_call:
    inputs:
      docker_files_name:
        description: Dockerfile's name
        required: true
        type: string

env:
  VERSION: ${{ vars.VERSION }}
  P4NAME: ${{ vars.P4NAME }}
  P4PORT: ${{ vars.P4PORT }}
  P4USER: ${{ secrets.P4USER }}
  P4PASSWD: ${{ secrets.P4PASSWD }}
  P4HOME: ${{ vars.P4HOME }}
  P4ROOT: ${{ vars.P4HOME }}/${{ vars.P4NAME }}
  CASE_INSENSITIVE: ${{ vars.CASE_INSENSITIVE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            docker build \
             -t $IMAGE_NAME \
             --build-arg VERSION=$VERSION \
             --build-arg P4NAME=$P4NAME \
             --build-arg P4PORT=$P4PORT \
             --build-arg P4USER=$P4USER \
             --build-arg P4PASSWD=$P4PASSWD \
             --build-arg P4HOME=$P4HOME \
             --build-arg P4ROOT=$P4ROOT \
             --build-arg CASE_INSENSITIVE=$CASE_INSENSITIVE \
             -f ./build/${{ inputs.docker_files_name }} ./build
