name: test

on:
  workflow_call:
    inputs:
      docker_files_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version_substr:
        type: string
      version:
        required: true
        type: string
      p4root:
        required: true
        type: string
      p4name:
        required: true
        type: string
      p4port:
        required: true
        type: string
      p4home:
        required: true
        type: string
      case_insensitive:
        required: true
        type: string


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
           docker build \
             -t ${{ inputs.image_name }} \
             --build-arg VERSION=${{ inputs.version }} \
             --build-arg P4NAME=${{ inputs.p4name }} \
             --build-arg P4PORT=${{ inputs.p4port }} \
             --build-arg P4USER=${{ secrets.P4USER }} \
             --build-arg P4PASSWD=${{ secrets.P4PASSWD }} \
             --build-arg P4HOME=${{ inputs.p4home }} \
             --build-arg P4ROOT=${{ inputs.p4root }} \
             --build-arg CASE_INSENSITIVE=${{ inputs.case_insensitive }} \
             -f ./build/${{ inputs.docker_files_name }} ./build